version: '3.8'

services:
  service-a:
    build:
      context: ./service_a
      dockerfile: Dockerfile
    container_name: ml-service-a
    ports:
      - "8000:8000"
    environment:
      - SERVICE_B_URL=http://service-b:8001/predict
      - LOG_LEVEL=INFO
      - PORT=8000
    depends_on:
      service-b:
        condition: service_healthy
    networks:
      - ml-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  service-b:
    build:
      context: ./service_b
      dockerfile: Dockerfile
    container_name: ml-service-b
    ports:
      - "8001:8001"
    environment:
      - LOG_LEVEL=INFO
      - PORT=8001
    networks:
      - ml-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ml-network:
    driver: bridge
    name: ml-microservices-network

volumes:
  app-data:
    name: ml-microservices-data