version: '3.8'

services:
  service-a:
    build: ./service_a
    ports:
      - "8000:8000"
    environment:
      - SERVICE_B_URL=http://service-b:8001/predict
      - LOG_LEVEL=WARNING
      - PORT=8000
    depends_on:
      service-b:
        condition: service_healthy
    networks:
      - ml-network
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  service-b:
    build: ./service_b
    ports:
      - "8001:8001"
    environment:
      - LOG_LEVEL=WARNING
      - PORT=8001
    networks:
      - ml-network
    restart: always
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ml-network:
    driver: bridge

volumes:
  app-data:
